import { CharacterStats } from './types';

// World Settings
export const TILE_SIZE = 50;
export const WORLD_WIDTH = 2000;
export const WORLD_HEIGHT = 2000;
export const FPS = 60;

// Gameplay Settings
export const MAX_AMMO = 3;
export const RELOAD_SPEED_BASE = 60; // Frames per ammo tick (approx 1s)
export const GEM_SPAWN_RATE = 300; // Frames (5s)
export const RESPAWN_TIME = 180; // Frames (3s)
export const WIN_GEM_COUNT = 10;

// Characters
export const CHARACTERS: CharacterStats[] = [
  {
    id: 'neon-ninja',
    name: 'Cyber Ken',
    role: 'Skirmisher',
    hp: 3200,
    maxHp: 3200,
    speed: 6.5,
    damage: 800,
    reloadTime: 40,
    range: 350,
    projectileSpeed: 18,
    projectileSize: 20,
    projectileCount: 1,
    spread: 0,
    color: '#00f3ff',
    description: 'A fast melee-hybrid fighter who throws cyber-shurikens.',
    superChargeRate: 25,
  },
  {
    id: 'tank-top',
    name: 'Chrome Dome',
    role: 'Tank',
    hp: 5500,
    maxHp: 5500,
    speed: 4.5,
    damage: 300,
    reloadTime: 55,
    range: 300,
    projectileSpeed: 14,
    projectileSize: 10,
    projectileCount: 5,
    spread: 0.4, // Shotgun spread
    color: '#ff00ff',
    description: 'Heavy unit with a shotgun arm. High health, short range.',
    superChargeRate: 15,
  },
  {
    id: 'viper',
    name: 'Viper',
    role: 'Sniper',
    hp: 2400,
    maxHp: 2400,
    speed: 5.0,
    damage: 1800,
    reloadTime: 90,
    range: 900,
    projectileSpeed: 30,
    projectileSize: 15,
    projectileCount: 1,
    spread: 0,
    color: '#fcee0a',
    description: 'Long-range precision sniper. Very low HP but high impact.',
    superChargeRate: 35,
  },
  {
    id: 'glitch',
    name: 'Glitch',
    role: 'Support',
    hp: 3600,
    maxHp: 3600,
    speed: 5.5,
    damage: 600,
    reloadTime: 30,
    range: 500,
    projectileSpeed: 12,
    projectileSize: 25,
    projectileCount: 1,
    spread: 0.1,
    color: '#00ff99',
    description: 'Fires erratic energy orbs that linger briefly.',
    superChargeRate: 20,
  },
  {
    id: 'inferno',
    name: 'Inferno',
    role: 'Skirmisher',
    hp: 4000,
    maxHp: 4000,
    speed: 5.8,
    damage: 200,
    reloadTime: 5, // Continuous fire feel
    range: 250,
    projectileSpeed: 10,
    projectileSize: 30,
    projectileCount: 1,
    spread: 0.2,
    color: '#ff4500',
    description: 'Spews cyber-flames. Short range, rapid tick damage.',
    superChargeRate: 5,
  },
  {
    id: 'doc-drone',
    name: 'Doc Drone',
    role: 'Support',
    hp: 3000,
    maxHp: 3000,
    speed: 5.5,
    damage: 500,
    reloadTime: 45,
    range: 600,
    projectileSpeed: 15,
    projectileSize: 15,
    projectileCount: 1,
    spread: 0,
    color: '#ffffff',
    description: 'Heals allies when shooting them (not implemented yet), hurts enemies.',
    superChargeRate: 20,
  },
  {
    id: 'knuckles',
    name: 'Knuckles',
    role: 'Tank',
    hp: 6000,
    maxHp: 6000,
    speed: 6.0, // Fast tank, but melee only
    damage: 1200,
    reloadTime: 30,
    range: 100, // Pure melee
    projectileSpeed: 0, // Hitscan box essentially
    projectileSize: 50,
    projectileCount: 1,
    spread: 0,
    color: '#8b0000',
    description: 'Melee powerhouse. Must get close to deal damage.',
    superChargeRate: 25,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    role: 'Assassin',
    hp: 2800,
    maxHp: 2800,
    speed: 7.0,
    damage: 1000,
    reloadTime: 40,
    range: 150,
    projectileSpeed: 20,
    projectileSize: 10,
    projectileCount: 1,
    spread: 0,
    color: '#4b0082',
    description: 'Invisible when not attacking (concept). Fast burst damage.',
    superChargeRate: 30,
  },
  {
    id: 'boombox',
    name: 'Boombox',
    role: 'Skirmisher',
    hp: 3800,
    maxHp: 3800,
    speed: 5.2,
    damage: 900,
    reloadTime: 60,
    range: 600,
    projectileSpeed: 12,
    projectileSize: 18,
    projectileCount: 2, // Throws 2 bombs
    spread: 0.2,
    color: '#ff69b4',
    description: 'Throws sonic grenades over walls.',
    superChargeRate: 20,
  },
  {
    id: 'architect',
    name: 'Architect',
    role: 'Support',
    hp: 3400,
    maxHp: 3400,
    speed: 5.0,
    damage: 400,
    reloadTime: 20,
    range: 700,
    projectileSpeed: 20,
    projectileSize: 12,
    projectileCount: 1,
    spread: 0,
    color: '#daa520',
    description: 'Builder class. Attacks are weak rivet gun shots.',
    superChargeRate: 15,
  },
];
